apiVersion: apps/v1
Kind: Deployment
metadata:
  name: orders-app
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: tsaisreekar/orders-app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
