apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080   # accessible on app-server:30080
